### ISSUE TITLE
Discord Modals error

### ISSUE THREAD

**Issue by Its-SheldonDev** [002-sans/Naoki-Bot-Perso#2]
Quand je fais n'importe quelle commande avec un modals discord (Menu déroulant), si je selectionne quelque chose, j'ai cette erreur :

TypeError: channel.isText is not a function

**Comment by LGDFR** [comment]
Tu as le patch qui a était déployé

**Comment by Its-SheldonDev** [comment]
Yes, merci, j'avais pas vu ^^
